### ISSUE TITLE
Support static files

### ISSUE THREAD

**Issue by jpgarcia** [matc4/react-native-svg-uri#1]
Hi @matc4 the library looks great! 

Do you have any plans to support static file sources like:

```JSX
<SvgUri width={150} height={150} source={require('@images/file.svg')} />
``` 
Thanks!

**Comment by matc4** [comment]
Hello, yes, i am planning to add support for static files, i will let you know when it's ready.

**Comment by jpgarcia** [comment]
I'm going to send you a PR right away with this feature implemented

**Comment by matc4** [comment]
Great!. Thanks!
