### ISSUE TITLE
Change SVG properties with the style

### ISSUE THREAD

**Issue by SandroMachado** [matc4/react-native-svg-uri#25]
Is it possible to change/override/add properties to the SVG using the style (or other) property? Something like `<SvgUri style={{ fill="#123456"...`? 

For instance, I have an `SVG` with a `path` and I want to change `fill` colour to my own colour in the `JSX`.

**Comment by adrienbataille** [comment]
@SandroMachado for the fill property, this PR #11 is already pending. I'm waiting for this option too!

**Comment by SandroMachado** [comment]
👍

**Comment by matc4** [comment]
Already solved in the PR of @henrikra.
Use the fill prop directly.

**Comment by dguillamot** [comment]
@matc4 Hi, is it possible to npm publish the version with the fill prop? Thanks!
