### ISSUE TITLE
Use peerDependencies

### ISSUE THREAD

**Issue by dantman** [matc4/react-native-svg-uri#28]
`react-native-svg` has a mess of complicated version restrictions:

> * react-native-svg >= 3.2.0 only supports react-native >= 0.29.0
> * react-native-svg >= 4.2.0 only supports react-native >= 0.32.0
> * react-native-svg >= 4.3.0 only supports react-native >= 0.33.0
> * react-native-svg >= 4.4.0 only supports react-native >= 0.38.0 and react >= 15.4.0
> * react-native-svg >= 4.5.0 only supports react-native >= 0.40.0 and react >= 15.4.0

The primary changes seem to be related to compatibility with react-native, not the api used by this package. It would probably be best if this package used a loose peerDependency instead of depending on react-native-svg directly.

**Comment by matc4** [comment]
Fix in the last release!
