### ISSUE TITLE
Loading SVGs locally is completely broken

### ISSUE THREAD

**Issue by tonydiepenbrock** [matc4/react-native-svg-uri#36]
This seems like an entirely different issue than #20 so I made a separate open issue.

The same SVGs work if I use the uri property on a remote host, but do not work and show the "TypeError: invalid svg" error if I use the require syntax.

An example is the canonical tiger SVG that everybody uses for testing their implementations:
https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg

This tiger fails with the same error message when using require, but works when using uri. In fact, I haven't been able to get even the simplest SVG to work using require.

With a simple example (from your README.md), I see the following:

`TypeError: unsupported file type
    at lookup (/Users/tonydiepenbrock/rn/node_modules/image-size/lib/index.js:35:9)
    at /Users/tonydiepenbrock/rn/node_modules/image-size/lib/index.js:93:22
    at /Users/tonydiepenbrock/rn/node_modules/image-size/lib/index.js:50:9
    at /Users/tonydiepenbrock/rn/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)`

for the very simple example below:

```
<Svg
    height="100"
    width="100"
>
    <Circle
        cx="50"
        cy="50"
        r="50"
        fill="pink"
    />
</Svg>
```

Right now, loading SVGs "locally" seems to be completely broken.

**Comment by phanhoangloc** [comment]
It happened to me too. It works by using URIs but does not work with static files

package.json
```json
{
  "react-native-svg": "4.4.0", 
  "react-native-svg-uri": "1.2.0"
}
```
