### ISSUE TITLE
Fill getting added to all svg elements, even when fill = none

### ISSUE THREAD

**Issue by kengorab** [matc4/react-native-svg-uri#39]
I have this up-arrow svg which I got from [the material design site](https://material.io/icons/#ic_arrow_upward):

```svg
<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h24v24H0V0z" fill="none"/>
    <path d="M4 12l1.41 1.41L11 7.83V20h2V7.83l5.58 5.59L20 12l-8-8-8 8z" fill="#000000"/>
</svg>
```

which looks like this:
<img width="50" alt="screen shot 2017-02-24 at 10 34 36 pm" src="https://cloud.githubusercontent.com/assets/6582067/23328142/d5263ed6-fae8-11e6-97db-433ed821f5ac.png">

You'll notice that it has two `path` elements, one with a fill of solid black and one with a fill of "none". When I try to use this svg in the app, I do it like so:

```jsx
<SvgUri
    width={24}
    height={24}
    fill="#ff00ff"
    source={require('./ic_arrow_upward.svg')}
/>
```

I'd expect this to produce an icon like this:
<img width="50" alt="screen shot 2017-02-24 at 10 35 20 pm" src="https://cloud.githubusercontent.com/assets/6582067/23328147/efd4f308-fae8-11e6-828c-a51aa57cfb3e.png">

but instead it ends up looking like this:
<img width="50" alt="screen shot 2017-02-24 at 10 36 00 pm" src="https://cloud.githubusercontent.com/assets/6582067/23328148/f762113c-fae8-11e6-9a10-da83d5e4e795.png">

This is because when applying the `fill` attribute, the code sets it without first checking if it's set to "none".

**Comment by henrikra** [comment]
Just remove the other `path` from the SVG file. End result looks like this:
```xml
<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
    <path d="M4 12l1.41 1.41L11 7.83V20h2V7.83l5.58 5.59L20 12l-8-8-8 8z" fill="#000000"/>
</svg>
```

**Comment by matc4** [comment]
fix in the last release!
