### ISSUE TITLE
Will this work for animated SVGs?

### ISSUE THREAD

**Issue by richardgill** [matc4/react-native-svg-uri#4]
Such amazing work to make this! Do you know if it will support an animated SVG?

**Comment by matc4** [comment]
Hello @richardgill, this lib depends on react-native-svg, so, if Animation is possible in that library it will be possible here.

**Comment by Introvertuous** [comment]
I do not believe they are, but you can wrap your svg in a [React.Animated](https://facebook.github.io/react-native/docs/animated.html) component.
