### ISSUE TITLE
Cant display SVG

### ISSUE THREAD

**Issue by juanmendez90** [matc4/react-native-svg-uri#46]
Hi,

I am trying to reproduce the sample code in the readme but i am getting the following error. 

![captura de pantalla 2017-04-07 a la s 17 00 04](https://cloud.githubusercontent.com/assets/8220448/24817653/b681b7a8-1bb3-11e7-9729-fb5b30ef9c8a.png)

Here is the code of my index.ios

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';

import SvgUri from 'react-native-svg-uri';

export default class moneyPocket extends Component {
  render() {
    return (
      <View style={styles.container}>
        <SvgUri
            width="200"
            height="200"
            source={{uri:'http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg'}}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('moneyPocket', () => moneyPocket);
```

I am using the following version of each package:

- react: 16.0.0-alpha.6,
- react-native: 0.43.2,
- react-native-svg-uri: 1.2.0
- react-native-svg: 4.6.1,

thanks

**Comment by aranda-adapptor** [comment]
I have the same problem with fetching SVG on iOS (only tested simulator so far). The same code works for Android but there looks to be a problem with isomorphic-fetch for iOS.

**Comment by aranda-adapptor** [comment]
Ok looks like isomorphic-fetch was a red herring! Problem (for me) was actually just iOS requiring `https` or adding an exception for known domains:

See https://facebook.github.io/react-native/docs/network.html

> By default, iOS will block any request that's not encrypted using SSL. If you need to fetch from a cleartext URL (one that begins with http) you will first need to add an App Transport Security exception. If you know ahead of time what domains you will need access to, it is more secure to add exceptions just for those domains; if the domains are not known until runtime you can disable ATS completely. Note however that from January 2017, Apple's App Store review will require reasonable justification for disabling ATS. See Apple's documentation for more information.

Note that `thenewcode` supports https (https://thenewcode.com/assets/images/thumbnails/homer-simpson.svg), so I suggest the examples and README should be updated to to avoid new users running into this issue!
