### ISSUE TITLE
Programmatically update fill. SetNativeProps ?

### ISSUE THREAD

**Issue by Thomeuxe** [matc4/react-native-svg-uri#49]
Hello !

I would like to update the fill the fill of a svg. How can I manage to do that with some kind of direct manipulation ?

Thank you !

**Comment by matc4** [comment]
Hello, the fill prop does not work for you?

**Comment by bmoreira10** [comment]
@matc4 when i use the svgXmlData, it works but it gives black color only , i have on the svgXmlData '<g fill="#474A4D">' it shows black and not kinda grey and if i try to use fill='#474A4D' it doesnt work either

**Comment by matc4** [comment]
Check in the new release. Thanks!
