### ISSUE TITLE
TouchEvent.obtain parameters error in RN 0.44 (proposed fix inside)

### ISSUE THREAD

**Issue by Krisztiaan** [matc4/react-native-svg-uri#52]
`SvgView:126`
```
TouchEvent.obtain(
                mTargetTag,
                type,
                ev,
                System.nanoTime(),
                ev.getX(),
                ev.getY(),
                mTouchEventCoalescingKeyHelper));
```

**Comment by matc4** [comment]
Hello, maybe this issue is for react-native-svg ?

**Comment by Krisztiaan** [comment]
You are right, sorry for my lazyness!

**Comment by danielreuterwall** [comment]
This is now fixed in react-native-svg, https://github.com/react-native-community/react-native-svg/pull/316.
Any chance we could get a new release with updated dependencies is this component works with 0.44?
