### ISSUE TITLE
 how can I pass the SVG as String directly?

### ISSUE THREAD

**Issue by androidluyang** [matc4/react-native-svg-uri#61]
how can I pass the SVG as String directly?

**Comment by matc4** [comment]
svgXmlData prop

**Comment by ithustle** [comment]
`logotipoBranco` variable has a xml string svg and doesn't work.

```
<SvgUri 
         width="100"
         height="100"
         svgXmlData={logotipoBranco}
/>
```

Any help, @matc4 ?

**Comment by alexmcode** [comment]
Same problem here +1

What worked for me was to just download the svg file and pass it as a string to svgXmlData prop:
`fetch('http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg')`
`      .then( r => r.text())`
 `     .then( r => {`
  `      this.setState({ r })`
   `   })`
    `  .catch( err => console.log('ERR', err))`
