### ISSUE TITLE
Fill is not working

### ISSUE THREAD

**Issue by DiegoGallegos4** [matc4/react-native-svg-uri#63]
I add fill to SVGUri component but is not filling the svg. What I did to make it is added on **index.js** (on package) on the **obtainComponentAtts** and do this: 
```javascript
....
if(this.props.fill){
   componentAtts.fill = this.props.fill;
}
return componentAtts;
```

Why isn't implemented like this? But rather expecting to change the svg element attribute. What if the element doesn't have the fill property? This will make sense in the case the fill should be selective but its not possible with this component.

I see it does have any support the last couple of months. Let me know if I can drop in as a collaborator.

**Comment by matc4** [comment]
Check in the new version. Thanks!
