### ISSUE TITLE
react-native-svg 5.2.0 supprot

### ISSUE THREAD

**Issue by dsvgit** [matc4/react-native-svg-uri#64]
Are you going to support react-native-svg 5.2.0 version?

**Comment by danielreuterwall** [comment]
As of React Native 0.46 we actually need react-native-svg 5.3.0 which has this fix:
[https://github.com/react-native-community/react-native-svg/pull/393](https://github.com/react-native-community/react-native-svg/pull/393)

I tried to updated the peerDependency to react-native-svg 5.3.0 and it seems to be working fine.

**Comment by hssrrw** [comment]
Waiting for https://github.com/matc4/react-native-svg-uri/pull/67 to be merged to fix the issue

**Comment by entropitor** [comment]
@matc4 Are you still maintaining this library? If so, can you merge #67 to fix the issue?

**Comment by gl0om** [comment]
waiting for a merge too

**Comment by herman-rogers** [comment]
Waiting for this too - you can add some collaborators to help out. I'm sure we / they wouldn't mind.

**Comment by BerndSchrooten** [comment]
For the meantime you can use the package `@datacamp/react-native-svg-uri`. It also has other improvements like classes. I'll make a PR soon.

**Comment by matc4** [comment]
Fix in the last release!. Thanks!
