### ISSUE TITLE
Need "Draw over other apps" permission on Android

### ISSUE THREAD

**Issue by mtr1012** [matc4/react-native-svg-uri#69]
I use your library to display svg image on ios normaly but on android its required "Draw over other apps" permission. can you explain this ?

**Comment by Crash--** [comment]
This library has no native code. So the issue may come from `react-native-svg` itself. But I suspect that you run your app in dev mode, and in dev mode, React-Native needs "Draw over other app" (see https://github.com/facebook/react-native/issues/5886#issuecomment-200837654)

**Comment by matc4** [comment]
As @Crash-- mentioned, this library doesn't have native code.

**Comment by softwaregal** [comment]
after adding the react-native-svg library my app asks for permission to overlay over other apps.This calls for a scary user experience. And i do not require to overlay over other apps.Is this intended behaviour? If not how can i fix this?

**Comment by matc4** [comment]
Hello @softwaregal , check the problem in **react-native-svg** library issues. This library has no native code.
