### ISSUE TITLE
Problem with Rect.js "Unable to resolve module"

### ISSUE THREAD

**Issue by kylanhurt** [matc4/react-native-svg-uri#71]
According to the team at react-native-svg, line 3 of Rect.js needs to be changed to the following:
`import createReactNativeComponentClass from 'react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass'`

![image](https://user-images.githubusercontent.com/6249205/28691431-c33a55ac-72d1-11e7-8f0d-50f2033dbf60.png)

**Comment by klaaz0r** [comment]
Ahh yes, had the same issue check out this PR https://github.com/matc4/react-native-svg-uri/pull/67 the problem is that the current dependencies from react-native-svg-uri do not match up with the version of react-native-svg

**Comment by JavRok** [comment]
+1 Please update the react-native-svg version. I had to do it manually because it was breaking my react native app. In the package.json, line 58:
 "dependencies": {
    "react-native-svg": "^4.3.1",  --> CHANGE TO ^5.4.1

It works for me. 

Thanks

**Comment by bradstimpson** [comment]
@JavRok I manually changed the dependency in the react-native-svg-uri package.json but am still getting this error.  Did you make any other changes?

**Comment by t4sk** [comment]
`npm install --save react-native-svg-uri`
manually change the dependency, as mentioned by @JavRok 
`npm install` again

did the trick for me.

**Comment by JavRok** [comment]
Yeah, when changing manually a version in package.json, you have to tell npm to update the node module, by running `npm update `
I don't think what @t4sk did is necessary, but also works.

**Comment by gitlovenotwar** [comment]
Please update the package.json of this repo. Had to manually update.

**Comment by mehdijjz** [comment]
I am using `"react-native-svg": "^5.4.1"` and it's still not working for me

**Comment by matc4** [comment]
Fix in the last release

**Comment by popaulina** [comment]
@matc4 I still have this issue on the most recent version.

**Comment by NickBefore** [comment]
@popaulina Me too.

**Comment by tobiastornros** [comment]
Me too

**Comment by JavRok** [comment]
#metoo
