### ISSUE TITLE
Need updates

### ISSUE THREAD

**Issue by CYB3RL1F3** [matc4/react-native-svg-uri#84]
Hello,

I recon the component needs to be updated to be supported by React 16 and React Native 0.49.

I tried to install the latest version of react-native-svg-ui and react-native-svg, and I got an error mentionning PropTypes doesn't exists. I looked at it and noticed that PropTypes was still imported from 'react', that is deprecated and now impossible to do.

I "manually" fixed the issue, but now I get another error : "Raw text cannot be used outside a <Text> tag". 

Once I close the error message, the svg is well rendered. If I remove the component it works well.

```
import arrow from 'assets/svg/arrow.svg';
```

```
<View style={styles.arrow}>
          <SvgUri source={arrow} width="16" height="16" />
        </View>
```

Is it possible to upgrade, to render it compatible with the latest versions of React Native ?

<img width="258" alt="capture d ecran 2017-10-20 a 18 04 10" src="https://user-images.githubusercontent.com/22372879/31830750-7cf74d38-b5c1-11e7-9cf6-9a707e543e97.png">

Thanks a lot :)

**Comment by lettertwo** [comment]
From my testing, I've noticed that this error isn't logged if whitespace is stripped from the svg.

I haven't tested this, but it looks to me like [this commit](https://github.com/matc4/react-native-svg-uri/commit/331b78e887821ef75cc8d27159b2a74b632ac5b1#diff-168726dbe96b3ce427e7fedce31bb0bc) might fix this (at least in my case).

**Comment by nickjohnson-dev** [comment]
I have tested the changes from the commit by @lettertwo, and it fixed the problem in my own project.

If we could get a patch release with this fix ASAP, that would be awesome.

@matc4 Thanks for taking the time to create this library. It's really helpful!

**Comment by matc4** [comment]
Ready!
